version: "3.9"
services:
  graphite:
    image: graphiteapp/graphite-statsd:latest
    container_name: "graphite"
    ports:
      - 3001:80
      - 2003:2003
      - 8125:8125
    networks:
      - monitoring-grid

  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - graphite
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - monitoring-grid

networks:
  monitoring-grid:
    name: monitoring-grid-net